[build]
  publish = "."

[[redirects]]
  from = "/clients"
  to = "/pages/clients.html"
  status = 200

[[redirects]]
  from = "/workers"
  to = "/pages/workers.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/pages/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/pages/contact.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/pages/privacy.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
